Python3 support
glencoesoftware/omero-user-token pull request #1
Opened 2020-03-24 10:27 UTC by emilroz

2020-03-24 10:48 UTC, chris-allan requested changes

2020-03-24 10:48 UTC, chris-allan commented on omero_user_token/__init__.py
> +from configparser import ConfigParser
https://python-future.org/compatible_idioms.html#configparser

2020-04-29 12:15 UTC, emilroz commented on omero_user_token/__init__.py
> +from configparser import ConfigParser
ef498e7

2020-05-04 15:40 UTC, chris-allan approved these changes

2020-05-04 15:41 UTC, merged